import {
  AngularAppEngine,
  createRequestHandler,
  ɵsetAngularAppEngineManifest as setAngularAppEngineManifest,
} from '@angular/ssr';

// @ts-expect-error Generated by Angular build pipeline for SSR runtime.
import appEngineManifest from './angular-app-engine-manifest.mjs';

setAngularAppEngineManifest(appEngineManifest);

const angularApp = new AngularAppEngine();

export const reqHandler = createRequestHandler(async (req: Request) => {
  return angularApp.handle(req);
});

export default reqHandler;
