name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build

      - name: Prepare GitHub Pages files
        run: |
          sed -i 's#<base href="/">#<base href="/seo-ia123/">#' docs/browser/index.html
          sed -i 's#<link rel="stylesheet" href="/#<link rel="stylesheet" href="/seo-ia123/#' docs/browser/index.html
          sed -i 's#<script src="/#<script src="/seo-ia123/#' docs/browser/index.html
          cp docs/browser/index.html docs/browser/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/browser
          force_orphan: true
